import type { Metadata } from "next";
import "@repo/ui/globals.css";
import "./globals.css";
import { ThemeProvider } from "@repo/ui/providers/theme";
import { QueryProvider } from "@repo/ui/providers/query";
import { Toaster } from "@repo/ui/components/toaster";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  
  return (
    <html className="light" lang="en" suppressHydrationWarning>
      {/* <head>
        <script src="https://unpkg.com/react-scan/dist/auto.global.js" ></script>
      </head> */}
      <body>
        <ThemeProvider>
          <QueryProvider>
            {children}
            <Toaster />
          </QueryProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
